name: Dayt CI Tests

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner
    # NEW! Adds postgres service. Must come before `steps`.
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby # An action to install Ruby and gems
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Yarn install
        run: yarn install --frozen-lockfile
